import { ChevronLeft, ChevronRight, Loader2, Search } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../api/client";
import { AnalystLayout } from "../components/PortalLayouts";

export default function FilaAuditoria({ onLogout }) {
  const navigate = useNavigate(); const [busca, setBusca] = useState(""); const [pagina, setPagina] = useState(1);
  const [dados, setDados] = useState({ itens: [], total: 0, por_pagina: 20 }); const [carregando, setCarregando] = useState(true); const [erro, setErro] = useState("");
  useEffect(() => { const timer = setTimeout(() => { setCarregando(true); api.get("/inscricoes/auditoria/fila", { params: { busca, pagina } }).then(({ data }) => setDados(data)).catch((err) => setErro(err.response?.data?.detail || "Não foi possível carregar a fila.")).finally(() => setCarregando(false)); }, 250); return () => clearTimeout(timer); }, [busca, pagina]);
  const inicio = dados.total ? (pagina - 1) * dados.por_pagina + 1 : 0; const fim = Math.min(pagina * dados.por_pagina, dados.total);
  return <AnalystLayout onLogout={onLogout}><div className="analyst-page"><header><div><p className="eyebrow">AUDITORIA</p><h1>Fila de Trabalho de Auditoria</h1></div><span className="status-chip">{dados.total} PENDENTE{dados.total === 1 ? "" : "S"}</span></header><div className="table-tools"><label><Search size={17}/><input value={busca} onChange={(event) => { setBusca(event.target.value); setPagina(1); }} placeholder="Buscar candidato ou nº da inscrição" /></label></div>{erro && <div className="alert error-alert">{erro}</div>}<section className="data-panel"><table className="data-table"><thead><tr><th>Candidato</th><th>ID inscrição</th><th>Edital</th><th>Motivo</th><th>Enviada em</th><th></th></tr></thead><tbody>{carregando ? <tr><td colSpan="6" className="queue-empty"><Loader2 className="spin" size={18}/> Carregando fila...</td></tr> : dados.itens.length === 0 ? <tr><td colSpan="6" className="queue-empty">Nenhuma inscrição aguardando auditoria.</td></tr> : dados.itens.map((linha) => <tr key={linha.inscricao_id}><td><strong>{linha.candidato}</strong></td><td>#{linha.inscricao_id}</td><td>{linha.processo}</td><td><span className="table-badge">{linha.motivo}</span></td><td>{linha.data ? new Date(linha.data).toLocaleString("pt-BR") : "—"}</td><td><button className="row-action" title="Abrir auditoria" onClick={() => navigate(`/auditoria/${linha.inscricao_id}`)}><ChevronRight size={18}/></button></td></tr>)}</tbody></table><footer><span>Mostrando {inicio}–{fim} de {dados.total} inscrições</span><span className="queue-pagination"><button disabled={pagina === 1} onClick={() => setPagina((atual) => atual - 1)}><ChevronLeft size={16}/></button>{pagina}<button disabled={fim >= dados.total} onClick={() => setPagina((atual) => atual + 1)}><ChevronRight size={16}/></button></span></footer></section></div></AnalystLayout>;
}
